name: Calculator Build Regression Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        platformio update

    - name: Build native
      run: platformio run -e native -v

    # - name: Common software tests
    #   run: |
    #     platformio test -e native_common -v
    #     platformio test -e native_common_ci -v

    # - name: Ground software tests
    #   run: ./tools/run_ground_tests.sh

    # - name: Verify FSW Teensy builds
    #   run: |
    #     ./tools/verify_teensy_builds.sh

    # - name: Verify ADCS Teensy builds
    #   run: ./tools/verify_adcs_builds.sh
